//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelCreator
{
    using System;
    using System.Collections.Generic;
    
    public partial class wyroby
    {
        public int id { get; set; }
        public string indeks { get; set; }
        public string opis { get; set; }
        public string opis2 { get; set; }
        public bool aktywny { get; set; }
        public bool do_aktualizacji { get; set; }
        public int grupa { get; set; }
        public string wzor_etk { get; set; }
        public string opw { get; set; }
        public System.DateTime czasw { get; set; }
        public string opm { get; set; }
        public System.DateTime czasm { get; set; }
    }
}
